version: '3.7'

services:
  courier-management:
    build: .
    environment:
      - COURIER_APP=${COURIER_APP}
      - COURIER_MANAGEMENT_WORKING_DIR=${COURIER_MANAGEMENT_WORKING_DIR}
    ports:
      - "8086:80"
      - "8085:80"
      - "8089:80"
