// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: pushevent.proto

package push

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *anypb.Any `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *PushEvent) Reset() {
	*x = PushEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEvent) ProtoMessage() {}

func (x *PushEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEvent.ProtoReflect.Descriptor instead.
func (*PushEvent) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{0}
}

func (x *PushEvent) GetEvent() *anypb.Any {
	if x != nil {
		return x.Event
	}
	return nil
}

type OfferAccepted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerPhoneNumber string     `protobuf:"bytes,1,opt,name=customer_phone_number,json=customerPhoneNumber,proto3" json:"customer_phone_number,omitempty"`
	Offer               *OfferInfo `protobuf:"bytes,2,opt,name=offer,proto3" json:"offer,omitempty"`
}

func (x *OfferAccepted) Reset() {
	*x = OfferAccepted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferAccepted) ProtoMessage() {}

func (x *OfferAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferAccepted.ProtoReflect.Descriptor instead.
func (*OfferAccepted) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{1}
}

func (x *OfferAccepted) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *OfferAccepted) GetOffer() *OfferInfo {
	if x != nil {
		return x.Offer
	}
	return nil
}

type OfferRejected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerPhoneNumber string     `protobuf:"bytes,1,opt,name=customer_phone_number,json=customerPhoneNumber,proto3" json:"customer_phone_number,omitempty"`
	Offer               *OfferInfo `protobuf:"bytes,2,opt,name=offer,proto3" json:"offer,omitempty"`
}

func (x *OfferRejected) Reset() {
	*x = OfferRejected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferRejected) ProtoMessage() {}

func (x *OfferRejected) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferRejected.ProtoReflect.Descriptor instead.
func (*OfferRejected) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{2}
}

func (x *OfferRejected) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *OfferRejected) GetOffer() *OfferInfo {
	if x != nil {
		return x.Offer
	}
	return nil
}

type OfferInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OfferId     string `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	CourierId   string `protobuf:"bytes,2,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	CourierName string `protobuf:"bytes,3,opt,name=courier_name,json=courierName,proto3" json:"courier_name,omitempty"`
	Time        string `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *OfferInfo) Reset() {
	*x = OfferInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferInfo) ProtoMessage() {}

func (x *OfferInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferInfo.ProtoReflect.Descriptor instead.
func (*OfferInfo) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{3}
}

func (x *OfferInfo) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *OfferInfo) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *OfferInfo) GetCourierName() string {
	if x != nil {
		return x.CourierName
	}
	return ""
}

func (x *OfferInfo) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type RideStateArrived struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequesterPhoneNumber string    `protobuf:"bytes,1,opt,name=requester_phone_number,json=requesterPhoneNumber,proto3" json:"requester_phone_number,omitempty"`
	SenderPhoneNumber    string    `protobuf:"bytes,2,opt,name=sender_phone_number,json=senderPhoneNumber,proto3" json:"sender_phone_number,omitempty"`
	ReceiverPhoneNumber  string    `protobuf:"bytes,3,opt,name=receiver_phone_number,json=receiverPhoneNumber,proto3" json:"receiver_phone_number,omitempty"`
	Ride                 *RideInfo `protobuf:"bytes,4,opt,name=ride,proto3" json:"ride,omitempty"`
}

func (x *RideStateArrived) Reset() {
	*x = RideStateArrived{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideStateArrived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideStateArrived) ProtoMessage() {}

func (x *RideStateArrived) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideStateArrived.ProtoReflect.Descriptor instead.
func (*RideStateArrived) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{4}
}

func (x *RideStateArrived) GetRequesterPhoneNumber() string {
	if x != nil {
		return x.RequesterPhoneNumber
	}
	return ""
}

func (x *RideStateArrived) GetSenderPhoneNumber() string {
	if x != nil {
		return x.SenderPhoneNumber
	}
	return ""
}

func (x *RideStateArrived) GetReceiverPhoneNumber() string {
	if x != nil {
		return x.ReceiverPhoneNumber
	}
	return ""
}

func (x *RideStateArrived) GetRide() *RideInfo {
	if x != nil {
		return x.Ride
	}
	return nil
}

type RideStateCancelled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequesterPhoneNumber string    `protobuf:"bytes,1,opt,name=requester_phone_number,json=requesterPhoneNumber,proto3" json:"requester_phone_number,omitempty"`
	Ride                 *RideInfo `protobuf:"bytes,2,opt,name=ride,proto3" json:"ride,omitempty"`
	CancellationNote     string    `protobuf:"bytes,3,opt,name=cancellation_note,json=cancellationNote,proto3" json:"cancellation_note,omitempty"`
}

func (x *RideStateCancelled) Reset() {
	*x = RideStateCancelled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideStateCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideStateCancelled) ProtoMessage() {}

func (x *RideStateCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideStateCancelled.ProtoReflect.Descriptor instead.
func (*RideStateCancelled) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{5}
}

func (x *RideStateCancelled) GetRequesterPhoneNumber() string {
	if x != nil {
		return x.RequesterPhoneNumber
	}
	return ""
}

func (x *RideStateCancelled) GetRide() *RideInfo {
	if x != nil {
		return x.Ride
	}
	return nil
}

func (x *RideStateCancelled) GetCancellationNote() string {
	if x != nil {
		return x.CancellationNote
	}
	return ""
}

type RideStatePickedup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequesterPhoneNumber string    `protobuf:"bytes,1,opt,name=requester_phone_number,json=requesterPhoneNumber,proto3" json:"requester_phone_number,omitempty"`
	SenderPhoneNumber    string    `protobuf:"bytes,2,opt,name=sender_phone_number,json=senderPhoneNumber,proto3" json:"sender_phone_number,omitempty"`
	Ride                 *RideInfo `protobuf:"bytes,3,opt,name=ride,proto3" json:"ride,omitempty"`
}

func (x *RideStatePickedup) Reset() {
	*x = RideStatePickedup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideStatePickedup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideStatePickedup) ProtoMessage() {}

func (x *RideStatePickedup) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideStatePickedup.ProtoReflect.Descriptor instead.
func (*RideStatePickedup) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{6}
}

func (x *RideStatePickedup) GetRequesterPhoneNumber() string {
	if x != nil {
		return x.RequesterPhoneNumber
	}
	return ""
}

func (x *RideStatePickedup) GetSenderPhoneNumber() string {
	if x != nil {
		return x.SenderPhoneNumber
	}
	return ""
}

func (x *RideStatePickedup) GetRide() *RideInfo {
	if x != nil {
		return x.Ride
	}
	return nil
}

type RideStateDelivered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequesterPhoneNumber string    `protobuf:"bytes,1,opt,name=requester_phone_number,json=requesterPhoneNumber,proto3" json:"requester_phone_number,omitempty"`
	ReceiverPhoneNumber  string    `protobuf:"bytes,2,opt,name=receiver_phone_number,json=receiverPhoneNumber,proto3" json:"receiver_phone_number,omitempty"`
	Ride                 *RideInfo `protobuf:"bytes,3,opt,name=ride,proto3" json:"ride,omitempty"`
}

func (x *RideStateDelivered) Reset() {
	*x = RideStateDelivered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideStateDelivered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideStateDelivered) ProtoMessage() {}

func (x *RideStateDelivered) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideStateDelivered.ProtoReflect.Descriptor instead.
func (*RideStateDelivered) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{7}
}

func (x *RideStateDelivered) GetRequesterPhoneNumber() string {
	if x != nil {
		return x.RequesterPhoneNumber
	}
	return ""
}

func (x *RideStateDelivered) GetReceiverPhoneNumber() string {
	if x != nil {
		return x.ReceiverPhoneNumber
	}
	return ""
}

func (x *RideStateDelivered) GetRide() *RideInfo {
	if x != nil {
		return x.Ride
	}
	return nil
}

type RideStateSenderIsNotAvailable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequesterPhoneNumber string    `protobuf:"bytes,1,opt,name=requester_phone_number,json=requesterPhoneNumber,proto3" json:"requester_phone_number,omitempty"`
	SenderPhoneNumber    string    `protobuf:"bytes,2,opt,name=sender_phone_number,json=senderPhoneNumber,proto3" json:"sender_phone_number,omitempty"`
	Ride                 *RideInfo `protobuf:"bytes,3,opt,name=ride,proto3" json:"ride,omitempty"`
}

func (x *RideStateSenderIsNotAvailable) Reset() {
	*x = RideStateSenderIsNotAvailable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideStateSenderIsNotAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideStateSenderIsNotAvailable) ProtoMessage() {}

func (x *RideStateSenderIsNotAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideStateSenderIsNotAvailable.ProtoReflect.Descriptor instead.
func (*RideStateSenderIsNotAvailable) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{8}
}

func (x *RideStateSenderIsNotAvailable) GetRequesterPhoneNumber() string {
	if x != nil {
		return x.RequesterPhoneNumber
	}
	return ""
}

func (x *RideStateSenderIsNotAvailable) GetSenderPhoneNumber() string {
	if x != nil {
		return x.SenderPhoneNumber
	}
	return ""
}

func (x *RideStateSenderIsNotAvailable) GetRide() *RideInfo {
	if x != nil {
		return x.Ride
	}
	return nil
}

type RideStateReceiverIsNotAvailable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequesterPhoneNumber string    `protobuf:"bytes,1,opt,name=requester_phone_number,json=requesterPhoneNumber,proto3" json:"requester_phone_number,omitempty"`
	ReceiverPhoneNumber  string    `protobuf:"bytes,2,opt,name=receiver_phone_number,json=receiverPhoneNumber,proto3" json:"receiver_phone_number,omitempty"`
	Ride                 *RideInfo `protobuf:"bytes,3,opt,name=ride,proto3" json:"ride,omitempty"`
}

func (x *RideStateReceiverIsNotAvailable) Reset() {
	*x = RideStateReceiverIsNotAvailable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideStateReceiverIsNotAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideStateReceiverIsNotAvailable) ProtoMessage() {}

func (x *RideStateReceiverIsNotAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideStateReceiverIsNotAvailable.ProtoReflect.Descriptor instead.
func (*RideStateReceiverIsNotAvailable) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{9}
}

func (x *RideStateReceiverIsNotAvailable) GetRequesterPhoneNumber() string {
	if x != nil {
		return x.RequesterPhoneNumber
	}
	return ""
}

func (x *RideStateReceiverIsNotAvailable) GetReceiverPhoneNumber() string {
	if x != nil {
		return x.ReceiverPhoneNumber
	}
	return ""
}

func (x *RideStateReceiverIsNotAvailable) GetRide() *RideInfo {
	if x != nil {
		return x.Ride
	}
	return nil
}

type RideStateFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequesterPhoneNumber string    `protobuf:"bytes,1,opt,name=requester_phone_number,json=requesterPhoneNumber,proto3" json:"requester_phone_number,omitempty"`
	Ride                 *RideInfo `protobuf:"bytes,2,opt,name=ride,proto3" json:"ride,omitempty"`
}

func (x *RideStateFinished) Reset() {
	*x = RideStateFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideStateFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideStateFinished) ProtoMessage() {}

func (x *RideStateFinished) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideStateFinished.ProtoReflect.Descriptor instead.
func (*RideStateFinished) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{10}
}

func (x *RideStateFinished) GetRequesterPhoneNumber() string {
	if x != nil {
		return x.RequesterPhoneNumber
	}
	return ""
}

func (x *RideStateFinished) GetRide() *RideInfo {
	if x != nil {
		return x.Ride
	}
	return nil
}

// when requester adds a new location it should inform courier
type RideNewLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourierPhoneNumber string    `protobuf:"bytes,1,opt,name=courier_phone_number,json=courierPhoneNumber,proto3" json:"courier_phone_number,omitempty"`
	Ride               *RideInfo `protobuf:"bytes,2,opt,name=ride,proto3" json:"ride,omitempty"`
	LocationId         string    `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Location           string    `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *RideNewLocation) Reset() {
	*x = RideNewLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideNewLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideNewLocation) ProtoMessage() {}

func (x *RideNewLocation) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideNewLocation.ProtoReflect.Descriptor instead.
func (*RideNewLocation) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{11}
}

func (x *RideNewLocation) GetCourierPhoneNumber() string {
	if x != nil {
		return x.CourierPhoneNumber
	}
	return ""
}

func (x *RideNewLocation) GetRide() *RideInfo {
	if x != nil {
		return x.Ride
	}
	return nil
}

func (x *RideNewLocation) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *RideNewLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type RideInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId       string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LocationId      string `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	HumanReadableId string `protobuf:"bytes,3,opt,name=human_readable_id,json=humanReadableId,proto3" json:"human_readable_id,omitempty"`
	// name of the sender or receiver
	FullName string `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// phone number of sender or receiver
	PhoneNumber string `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Time        string `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *RideInfo) Reset() {
	*x = RideInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RideInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideInfo) ProtoMessage() {}

func (x *RideInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideInfo.ProtoReflect.Descriptor instead.
func (*RideInfo) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{12}
}

func (x *RideInfo) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RideInfo) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *RideInfo) GetHumanReadableId() string {
	if x != nil {
		return x.HumanReadableId
	}
	return ""
}

func (x *RideInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RideInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RideInfo) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type AnnouncementReceived struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type            int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	MessageType     int32  `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Text            string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Time            string `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	UserPhoneNumber string `protobuf:"bytes,7,opt,name=user_phone_number,json=userPhoneNumber,proto3" json:"user_phone_number,omitempty"`
}

func (x *AnnouncementReceived) Reset() {
	*x = AnnouncementReceived{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushevent_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnouncementReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementReceived) ProtoMessage() {}

func (x *AnnouncementReceived) ProtoReflect() protoreflect.Message {
	mi := &file_pushevent_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementReceived.ProtoReflect.Descriptor instead.
func (*AnnouncementReceived) Descriptor() ([]byte, []int) {
	return file_pushevent_proto_rawDescGZIP(), []int{13}
}

func (x *AnnouncementReceived) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnnouncementReceived) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnnouncementReceived) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AnnouncementReceived) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *AnnouncementReceived) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnnouncementReceived) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *AnnouncementReceived) GetUserPhoneNumber() string {
	if x != nil {
		return x.UserPhoneNumber
	}
	return ""
}

var File_pushevent_proto protoreflect.FileDescriptor

var file_pushevent_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x75, 0x73, 0x68, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x70, 0x75, 0x73, 0x68, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x37, 0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x2a, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x6a, 0x0a, 0x0d, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x32, 0x0a, 0x15,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x25, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x22, 0x6a, 0x0a, 0x0d, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x05,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x75,
	0x73, 0x68, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x6f, 0x66,
	0x66, 0x65, 0x72, 0x22, 0x7c, 0x0a, 0x09, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x19, 0x0a, 0x08, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x22, 0xd0, 0x01, 0x0a, 0x10, 0x52, 0x69, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x41,
	0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x16, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x13,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x15,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x22, 0x0a, 0x04, 0x72, 0x69, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x72, 0x69, 0x64, 0x65, 0x22, 0x9b, 0x01, 0x0a, 0x12, 0x52, 0x69, 0x64, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x16, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x22, 0x0a, 0x04, 0x72, 0x69, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x72, 0x69, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x74, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x11, 0x52, 0x69, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x50, 0x69, 0x63, 0x6b, 0x65, 0x64, 0x75, 0x70, 0x12, 0x34, 0x0a, 0x16, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2e,
	0x0a, 0x13, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22,
	0x0a, 0x04, 0x72, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x75, 0x73, 0x68, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x72, 0x69,
	0x64, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x12, 0x52, 0x69, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x16, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x32, 0x0a, 0x15, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x72, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x72, 0x69, 0x64, 0x65, 0x22, 0xa9, 0x01, 0x0a, 0x1d, 0x52, 0x69, 0x64, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x73, 0x4e, 0x6f, 0x74,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x16, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x2e, 0x0a, 0x13, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x22, 0x0a, 0x04, 0x72, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x75, 0x73, 0x68, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x72,
	0x69, 0x64, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x1f, 0x52, 0x69, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x73, 0x4e, 0x6f, 0x74, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x16, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x32, 0x0a,
	0x15, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x22, 0x0a, 0x04, 0x72, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x72, 0x69, 0x64, 0x65, 0x22, 0x6d, 0x0a, 0x11, 0x52, 0x69, 0x64, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x16, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x22, 0x0a, 0x04, 0x72, 0x69, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x72, 0x69, 0x64, 0x65, 0x22, 0xa4, 0x01, 0x0a, 0x0f, 0x52, 0x69, 0x64, 0x65, 0x4e, 0x65, 0x77,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x72, 0x69,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e,
	0x52, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x72, 0x69, 0x64, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xca, 0x01, 0x0a, 0x08,
	0x52, 0x69, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x68, 0x75, 0x6d, 0x61,
	0x6e, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0xc7, 0x01, 0x0a, 0x14, 0x41, 0x6e, 0x6e,
	0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x42, 0x12, 0x5a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pushevent_proto_rawDescOnce sync.Once
	file_pushevent_proto_rawDescData = file_pushevent_proto_rawDesc
)

func file_pushevent_proto_rawDescGZIP() []byte {
	file_pushevent_proto_rawDescOnce.Do(func() {
		file_pushevent_proto_rawDescData = protoimpl.X.CompressGZIP(file_pushevent_proto_rawDescData)
	})
	return file_pushevent_proto_rawDescData
}

var file_pushevent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pushevent_proto_goTypes = []interface{}{
	(*PushEvent)(nil),                       // 0: push.PushEvent
	(*OfferAccepted)(nil),                   // 1: push.OfferAccepted
	(*OfferRejected)(nil),                   // 2: push.OfferRejected
	(*OfferInfo)(nil),                       // 3: push.OfferInfo
	(*RideStateArrived)(nil),                // 4: push.RideStateArrived
	(*RideStateCancelled)(nil),              // 5: push.RideStateCancelled
	(*RideStatePickedup)(nil),               // 6: push.RideStatePickedup
	(*RideStateDelivered)(nil),              // 7: push.RideStateDelivered
	(*RideStateSenderIsNotAvailable)(nil),   // 8: push.RideStateSenderIsNotAvailable
	(*RideStateReceiverIsNotAvailable)(nil), // 9: push.RideStateReceiverIsNotAvailable
	(*RideStateFinished)(nil),               // 10: push.RideStateFinished
	(*RideNewLocation)(nil),                 // 11: push.RideNewLocation
	(*RideInfo)(nil),                        // 12: push.RideInfo
	(*AnnouncementReceived)(nil),            // 13: push.AnnouncementReceived
	(*anypb.Any)(nil),                       // 14: google.protobuf.Any
}
var file_pushevent_proto_depIdxs = []int32{
	14, // 0: push.PushEvent.event:type_name -> google.protobuf.Any
	3,  // 1: push.OfferAccepted.offer:type_name -> push.OfferInfo
	3,  // 2: push.OfferRejected.offer:type_name -> push.OfferInfo
	12, // 3: push.RideStateArrived.ride:type_name -> push.RideInfo
	12, // 4: push.RideStateCancelled.ride:type_name -> push.RideInfo
	12, // 5: push.RideStatePickedup.ride:type_name -> push.RideInfo
	12, // 6: push.RideStateDelivered.ride:type_name -> push.RideInfo
	12, // 7: push.RideStateSenderIsNotAvailable.ride:type_name -> push.RideInfo
	12, // 8: push.RideStateReceiverIsNotAvailable.ride:type_name -> push.RideInfo
	12, // 9: push.RideStateFinished.ride:type_name -> push.RideInfo
	12, // 10: push.RideNewLocation.ride:type_name -> push.RideInfo
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pushevent_proto_init() }
func file_pushevent_proto_init() {
	if File_pushevent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pushevent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferAccepted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferRejected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RideStateArrived); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RideStateCancelled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RideStatePickedup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RideStateDelivered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RideStateSenderIsNotAvailable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RideStateReceiverIsNotAvailable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RideStateFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RideNewLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RideInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pushevent_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnouncementReceived); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pushevent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pushevent_proto_goTypes,
		DependencyIndexes: file_pushevent_proto_depIdxs,
		MessageInfos:      file_pushevent_proto_msgTypes,
	}.Build()
	File_pushevent_proto = out.File
	file_pushevent_proto_rawDesc = nil
	file_pushevent_proto_goTypes = nil
	file_pushevent_proto_depIdxs = nil
}
